### ISSUE TITLE
Add support for audit-argument-checks package

### ISSUE THREAD

**Issue by pburke** [CollectionFS/DEPRECATING-cfs-file#5]
The audit-argument-checks package is used to enforce validating data submitted from the client. It seems to be an emerging best practice among Meteor developers. 

With the autit-argument-checks package installed, when I try to upload a file from the client by passing a URL, I get the following error:

    Exception while invoking method '_cfs_getUrlInfo' Error: Did not check() all arguments during call to '_cfs_getUrlInfo'

Removing the package solves the problem, but it would be nice if that were not necessary.

**Comment by aldeed** [comment]
Moved to [main repo](https://github.com/CollectionFS/Meteor-CollectionFS/issues/560).
